[package]
org = "dhanushka"
name = "fakeapp_police_check_api"
version = "0.1.0"
distribution = "2201.2.3"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId="mysql"
artifactId="mysql-connector-java"
version="8.0.20"